name: Android release

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: task-organizer
          path: app/build/outputs/apk/release/task-organizer.apk

  release:
    name: Release APK
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: task-organizer
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v0.1.15
        env:
          GITHUB_TOKEN: ${{ secrets.APK_BUILD_TOKEN }}
        with:
          tag_name: v0.1.${{ github.run_number }}
          name: Release v0.1.${{ github.run_number }}
          draft: false
          prerelease: false
          files: task-organizer.apk

#      - name: Update git tag
#        run: |
#          git tag -f latest
#          git push -f origin latest
#
#      - name: Delete Release
#        uses: cb80/delrel@latest
#        with:
#          tag: latest
#
#      - name: Create Release
#        uses: ncipollo/release-action@v1
#        with:
#          allowUpdates: true
#          artifacts: app/build/outputs/apk/release/*.apk
#          generateReleaseNotes: false
#          makeLatest: true
#          tag: "latest"