name: Build & Publish Release APK

on:
  push:
    tags:
      - 'v*'

jobs:
  apk:
    name: Generate apk
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Change gradle wrapper permissions
        run: chmod +x ./gradlew

      - name: Assemble debug
        run: ./gradlew assembleRelease


#      - name: Build project
#        run: |
#          mkdir -p app/build/outputs/apk/release
#          echo hello > app/build/outputs/apk/release/app-release-unsigned.apk
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/release/app-release-unsigned.apk
        env:
          GITHUB_TOKEN: ${{ secrets.APK_BUILD_TOKEN }}
#      - name: setup jdk
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'adopt'
#          java-version: '17'
#
#      - name: Change gradle wrapper permissions
#        run: chmod +x ./gradlew
#
#      - name: Build Release APK
#        run: ./gradlew assembleRelease
#      - name: Releasing using Hub
#        uses: r0user/release-apk@main
#        env:
#          GITHUB_TOKEN: ${{ secrets.APK_BUILD_TOKEN }}
#          APP_FOLDER: app