name: GitHub Actions Demo
run-name: ${{ github.actor }} is building a new release version
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Change gradle wrapper permissions
        run: chmod +x ./gradlew
      #
      #      - name: Assemble debug
      #        run: ./gradlew assembleDebug --stacktrace

      #      - name: Run Gradle build
      #        run: ./gradlew build
      #
      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload html lint reports
        uses: actions/upload-artifact@v3
        with:
          name: index.html
          path: app/build/reports/lint-results-debug.html

  package:
    name: generate apk
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Change gradle wrapper permissions
        run: chmod +x ./gradlew

      - name: Assemble debug
        run: ./gradlew assembleDebug

      - name: Upload apk
        uses: actions/upload-artifact@v3
        with:
          name: task-organizer.apk
          path: app/build/outputs/apk/debug/app-debug.apk